#!/bin/bash

rflag=
gflag=
bflag=
Bflag=
cflag=

while getopts rgBbc name
do
   case $name in
   r)    rflag=1;;
   g)    gflag=1;;
   b)    bflag=1;;
   B)    Bflag=1;;
   c)    cflag=1;;
   ?)    printf "Usage: %s: [-rgBbc]\n" "$0"
         exit 2;;
   esac
done

if [ ! -z "$cflag" ]; then
    make clean
fi
if [ ! -z "$bflag" ]; then
	bear -- make
fi
if [ ! -z "$Bflag" ]; then
	bear -- make debug
fi
if [ ! -z "$gflag" ]; then
	if [ -f /build/server_d ]; then
		./build/server_d
	else
		bear -- make debug
		./build/server_d
	fi
fi
if [ ! -z "$rflag" ]; then
	if [ -f /build/server ]; then
		./build/server
	else
		bear -- make
		./build/server
	fi
fi
